### ISSUE TITLE
Floating point overflow in single site model recalculation

### ISSUE THREAD

**Issue by sysbiogirl** [debbiemarkslab/EVcouplings#104]
I encountered these floating point errors when using the mean_field approximation algorithm to calculate coupling scores. Model file attached. 
[AIM2_HUMAN.model.zip](https://github.com/debbiemarkslab/EVcouplings/files/1633020/AIM2_HUMAN.model.zip)

```/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/matplotlib/font_manager.py:1297: UserWarning: findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/couplings/model.py:887: RuntimeWarning: overflow encountered in exp
  logZ = np.log(np.exp(x).sum())
/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/couplings/model.py:895: RuntimeWarning: overflow encountered in exp
  Z = np.exp(x).sum()
/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/couplings/model.py:896: RuntimeWarning: overflow encountered in exp
  P = np.exp(x) / Z
/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/couplings/model.py:896: RuntimeWarning: invalid value encountered in true_divide
  P = np.exp(x) / Z
/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/couplings/model.py:887: RuntimeWarning: overflow encountered in exp
  logZ = np.log(np.exp(x).sum())
/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/couplings/model.py:887: RuntimeWarning: overflow encountered in exp
  logZ = np.log(np.exp(x).sum())
/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/couplings/model.py:895: RuntimeWarning: overflow encountered in exp
  Z = np.exp(x).sum()```

**Comment by thomashopf** [comment]
Thanks for reporting Hailey! 

Can you also share the piece of code where you call the function, or was that during a pipeline run? If pipeline, would be great if you could post the path on Orchestra, or the alignment and config files on here too. Looks like it might be caused by a pathological alignment to me...

**Comment by sysbiogirl** [comment]
[AIM2_HUMAN.zip](https://github.com/debbiemarkslab/EVcouplings/files/1636952/AIM2_HUMAN.zip)
No problem! 

This was during a pipeline run. The Orchestra path is here: /groups/marks/users/hcambra/projects/human_death_fold/output/AIM2_HUMAN/couplings/AIM2_HUMAN.model

And I've attached the config and alignment files. 
[AIM2_HUMAN_config.txt](https://github.com/debbiemarkslab/EVcouplings/files/1636948/AIM2_HUMAN_config.txt)

**Comment by thomashopf** [comment]
Thanks Hailey - I'll have a look as soon as I can - probably will be this weekend

**Comment by sacdallago** [comment]
@kpgbrock just for reference

**Comment by thomashopf** [comment]
So this was actually a funky problem during inference of the independent model ... Because mean-field doesn't know lambda_h and lambda_J, the respective fields in the model are -1. In the CouplingsModel object, this performed as anti-regularization incentivizing the parameters to become as large as possible :D

Consequences of this problem: Mutation effects using independent model on mean-field couplings were garbage.

For now, in these cases (no proper lambda_h defined), the code uses a fallback lambda_h of 0.01 and infers the independent model using l2 regularization.

Conceptually, however, the inference of the independent model should also use pseudocounted f_i's for comparability (this is incidentally how I code the independent model in the very beginning, but at some point I threw it out). This cleaner solution is moved to #116 

For full reference, mutation effects from mean-field couplings should be treated with care since it looks like there might be some sign inversion.
