### ISSUE TITLE
atom_distance default should be named

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#111]
In https://github.com/debbiemarkslab/EVcouplings/blob/develop/config/sample_config_monomer.txt#L223 the default is "leave empty", which by inspecting the code seems to fallback on `Null`. This is not good practice. Either this field is boolean, or all options are named (e.g. default: minimum atom distance = MAD), and one of the options is defaulted (in this case MAD).

Should be addressed in v0.0.3

Opinions @thomashopf ?

**Comment by thomashopf** [comment]
No - the parameter is about what particular atom_filter is applied to the coordinate list, no filter being the default (aka None). The type of computed distance follows from that, but this is decidedly *not* a direct switch between minimum atom or C_alpha or any other distance function. I am updating the documentation a little to make this point more explicit, but there is nothing to be addressed here in implementation.

**Comment by sacdallago** [comment]
First: nice to have you bursting out with PRs and solutions :) Much appreciated.

About this particular issue: I understand. Let me change the question/issue then (and reopen, for the time being): what's the behavior for erroneous input? If I were to set this value to NOT None and NOT CA?

There are two options, from an SWE perspective:
- Fail --> throw an error
- Fallback to a default

The Fail option is perfectly fine, as well as the fallback but then it must be 100% clear what the expected behavior is and in case it's the default, what the default for that field is. I'm saying this precisely because asking around I have not gotten an answer to this, and I can't answer this question myself by reading around the code etc. These are things that users care about, and that make the difference between being frustrated with software vs knowing what's going on

**Comment by thomashopf** [comment]
Valid options are any PDB atom names, or lists thereof if one wants to ask more advanced questions (like minimum atom distance between backbone atoms etc). 
https://github.com/debbiemarkslab/EVcouplings/blob/develop/evcouplings/compare/pdb.py#L126

The problem is this discussion is moot. Obviously there is a lot of room for improvement everywhere and one could handle these things better and more robustly for every single parameter and step in the pipeline. But it takes someone to actually sit down and *do it* given all other time constraints and items on their TODO list.
