### ISSUE TITLE
Add optional --master config flag

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#122]
The EVcouplings server frontend spits out a stripped down config for the users to run on local instances. There are two approaches as to how the user could set the job to run locally:

1. Write environment specific parameters (e.g. databases, environment, dependencies, submitter,...) in the config file downloaded from the frontend (a lot of copy-pasting, error-prone if frequent).
2. We allow an option in evcouplings that takes in a "master" config (where the databases, environment,.... are defined) and overwrites OR, in general, uses all job-specific params (aka. the ones defined in the job config txt file). So: `evouplings --master master.txt job.txt`. This should be less error-prone, and if users have a config file of a previous job lying around, that should do as well.

An example of a config as it comes from the frontend is here: 
[job.txt](https://github.com/debbiemarkslab/EVcouplings/files/1687155/job.txt)

The full example of what you get from downloading a "job" template from evcouplings frontend: 
[example.zip](https://github.com/debbiemarkslab/EVcouplings/files/1687167/example.zip)

@thomashopf you likey likey or ney?

**Comment by thomashopf** [comment]
Certainly won't hurt to have this feature to apply a configuration delta to some other config file, could also be useful in other settings.

1) Has to be implemented the other way round though to be consistent with the logic of the command line processing (cf #117): The positional argument is the actual "master" config file, all other parameters override settings in there, i.e. the command line argument has to be sth. like
`evcouplings --substitute job.txt yourlocalconfig.txt`
to substitute the current job config *into* the master

2) The batch section, which is a configuration delta, in the master config needs to replaced entirely, or otherwise it all gets a bit confusing applying a delta to a delta

3) Any other command line parameters should be applied after the substitution

**Comment by sacdallago** [comment]
:) good. You point one has been a fiery debate between me and @b-schubert . I lean towards implementing it how you suggest, whereas @b-schubert leans toward what I wrote in the initial issue. Benni's point is: the expected behavior of the api is that the **JOB** is the last argument, as means of consistency. While I agree with this point to some extent, I think that the operation of overwriting something is an option, and conceptually having it the other way around is confusing.

So. Ultimately: I'd put it up for a vote.
- React with 👍  for `evouplings --master master.txt job.txt`
- React with 😆  for `evouplings --overwrite job.txt localconfig.txt`

Voters: @b-schubert @thomashopf @aggreen . I'll abstain, so no ties

**Comment by thomashopf** [comment]
@b-schubert Benni, could you please write out your full reasoning for --master? I currently don't understand why this would be a more consistent solution. 

The way I intended this was
* Job that runs = configuration you get after applying any changes to master config, and if you don't apply any flags, everything has to be inside the master config. When you run evcouplings -p RASH_HUMAN config.txt, the job itself is very much defined by selecting the protein -p and overriding that in the base config.
* the job.txt from the server itself is not a runnable configuration file but just a delta compared to some master configuration, so evcouplings <serverjob.txt> wouldn't work according to that logic - because then the base configuration becomes a flag and the changes you apply to it become the positional parameter

@aggreen Anna, any strong opinions on this?

I'll make a final call on this once we have discussed all aspects.

**Comment by sacdallago** [comment]
This must be done for 0.0.4 because it's advertised on the new web frontend. Should be a minor thing, but I have not yet started. Will work on it on the plane tonight/tomorrow

**Comment by thomashopf** [comment]
Parked for now
