### ISSUE TITLE
utils.helpers.range_overlap does not work correctly with negative numbers

### ISSUE THREAD

**Issue by b-schubert** [debbiemarkslab/EVcouplings#128]
the range_overlap function does not compute negative interval overlap correctly....

e.g.:
```
range_overlap((-1,-3), (-2, -4)) 
```
should return 1 but returns 0.  Should we fix that or can we just ignore it since we would never expect negative numbers?

**Comment by thomashopf** [comment]
Better to fix... looks like the problem is caused because start > end but it should be start < end.

Could either swap if given the wrong way round (but then becomes muddy what is inclusive/exclusive), or raise and InvalidParameterError if start >= end (and update documentation accordingly to make that constraint transparent).

**Comment by b-schubert** [comment]
resolved in PR #148 

- Function will through InvalidParameterError as suggested
