### ISSUE TITLE
Auto range not working when skipping align?

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#167]
Frank (in Chris' group) reports the following error:

- Conf: [PROT.txt](https://github.com/debbiemarkslab/EVcouplings/files/1995840/PROT.txt)
- stderr: [PROT_stderr.log](https://github.com/debbiemarkslab/EVcouplings/files/1995839/PROT_stderr.log)
- .failed: [PROT.failed.txt](https://github.com/debbiemarkslab/EVcouplings/files/1995846/PROT.failed.txt)

Notice that in the config I've changed all sensible data to `PROT`.

As you can tell, he is only interested in running the couplings, given that he already run align and the namespace is conserved etc.

My intuition is that in `global` the missing explicit `region` causes the error, given that the pipeline is executed not from the beginning @aggreen @thomashopf @b-schubert can you help out?

Thanks!

**edit**: I've asked Frank to change the config with an explicit range, I'll update this issue after that

**Comment by thomashopf** [comment]
The reason causing the crash is that the input alignment fed into the mean-field inference apparently doesn't contain a header of the form SEQID/start-end. We might want to raise an explicit exception when is the extraction of the header isn't successful.

But the reason the header isn't there is because an input user alignment should always be fed through the protocol "existing" in the align stage so it complies to the formatting requirements of the later stages (this is one of the very reasons the existing protocol is there).

I'll get in touch with Frank directly and sort this out with him.

**Comment by sacdallago** [comment]
Thanks @thomashopf , sorry for the confusion :) To my understanding, omitting the stage would use the "existing" protocol, but I was obviously wrong there 🙈 apologies!

**Comment by thomashopf** [comment]
No problem. Skipping really means skipping, and you can only skip in two ways:
* stages at the end can be left out (so e.g. you terminate at compare and don't go into fold)
* you can skip running a stage that has been run before (e.g. skip align and rerun couplings), and reuse its results

There is another mode of "semi-skipping" in the align and coupling stages where the computationally intensive parts are not run again (reuse_alignments or reuse_couplings set to True), but all the other post-processing is rerun; e.g. if one wants to reuse the same raw input alignment but apply a different gap threshold.
