### ISSUE TITLE
is there any protocol that we can follow?

### ISSUE THREAD

**Issue by lixingguang** [debbiemarkslab/EVcouplings#202]
why install the optional softwares is so complex?

**Comment by sacdallago** [comment]
Hi @lixingguang ,

unfortunately we can't control how external resources distribute their software 😞and every now and then the software gets distributed slightly differently. @nselem recently put together a nice [docker file](https://github.com/nselem/evcouplings/blob/master/ev_dependencies/Dockerfile) collecting all the dependencies (except [CNS solve](http://cns-online.org/cns_request/), which you need to get a license for).

You can either run that docker container and use a shared volume to a local folder OR copy-paste the commands after `RUN` and install the dependencies locally (supposing that you have a debian based system).

Also note that depending on what you want to do, only several dependencies are required, as on the [readme](https://github.com/debbiemarkslab/EVcouplings#external-software-tools). In broad terms, you will need the optional dependencies if you want to run fold. Otherwise you should be good to go.

Hope this helps.

**Comment by nselem** [comment]
Hello, 
I will be more than pleased to help you if you try my docker my file.
