### ISSUE TITLE
0.0.2 Release

### ISSUE THREAD

**Issue by b-schubert** [debbiemarkslab/EVcouplings#95]
Since EVcouplings has changed quit a bit over the last months, we should probably release a new official version. 

What do you think?

**Comment by thomashopf** [comment]
Yes we are definitely getting there - in terms of new features (EVcomplex integration, structure search with hmmsearch) I would say it ready.

Two important points are still missing though:

1) Must-have issue #96: Distribution of database files for EVcomplex (genome location, ID mapping). These are absolutely crucial for users to be able to use the complex pipeline, so minimally they should be available from the lab website for download using the database update tool). Even better (but ok if only later) would be inclusion of a script that generates the database files automatically.

2) I would be a lot happier if #64 is addressed in some way - either that file is on the horizon from SIFTS directly (would need checking), or we generate it ourselves.

**Comment by sacdallago** [comment]
@thomashopf @b-schubert @aggreen @kpgbrock 

**UPDATE**

We deploy 0.0.2 **now** and deploy 0.0.3 as scheduled in the milestone https://github.com/debbiemarkslab/EVcouplings/milestone/1

Reason: there are important bug fixes on the current develop branch that can't wait any longer. Meantime, we will be working exclusively on tests (until March)

IF no one has strong suggestions: by WED:
- bump all necessary version numbers (@b-schubert we need to remember where they all appear, last time we forgot `setup.py` if I'm not mistaken)
- create PR from dev to master
- release master with tag `0.0.2`

**Comment by aggreen** [comment]
I am currently fixing a couple more bugs in develop so NO DEPLOYMENT until
I say so

On Mon, Feb 12, 2018 at 6:03 PM, Christian Dallago <notifications@github.com

**Comment by thomashopf** [comment]
1. We are not having deadlines here
2. v0.0.2 goes out when it is ready - since Anna is taking the effort of testing & fixing, that call is up to her
3. We'll have a discussion about v0.0.3 release after v0.0.2 is out
4. We will not be working exclusively on tests.

**Comment by sacdallago** [comment]
@thomashopf Anna and I wrote the issue together yesterday :) so, no worries, the "now" was more abut whenever anna's done.

The "exclusively on test" is more to get some big chunk done by end of feb, so that we all have a common goal and can help out each other, since just doing this sporadically doesn't seem to bring us very far 😢  and this is also about the "deadlines", I think that for us here it's good to have some things delimited and know: ok, we will work _mostly_ on tests until feb now, and then it's again "up to discussion", also: everyone is testing different parts of the pipeline and it makes sense to have a mental date in which we come together and see where we are all standing.

I don't want to spawn any heated discussions :) I just think that there is some miscommunication from our side towards you, mostly because we are all in a room and things happen suuuper quickly and we don't want to submerge you with every little detail :) If we can move the EVcouplings team meetings to Thursday morning, would you be able to join from time to time?

**Comment by b-schubert** [comment]
Related to pypi deployment problems:

https://github.com/FaradayRF/faradayio/issues/35

**Comment by b-schubert** [comment]
Automatic deployment is now working. The problem was/is:

1) the pypi password cannot contain any special characters
2) travis encrypt has to be called in the master repository and not in a forked repository

Release v0.0.1 is now officially on pypi
